name: Push File To Ukrajinisation mod

on: commit

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pushes test file
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'core/assets/bundles/bundle_uk_UA.properties'
        destination_repo: 'Prosta4okua/Ukrajinisator'
        destination_folder: 'bundles'
        user_email: ${{ secrets.EMAIL_GITHUB }}
        user_name: 'Prosta4okua'
        commit_message: 'A custom message for the commit'
