
import java.text.*
import java.util.*

plugins{
    `java-library`
    `maven-publish`
    id("org.jetbrains.kotlin.jvm")
    id("org.jetbrains.kotlin.kapt")
}

val versionNumber = providers.gradleProperty("versionNumber").get()
val versionType = providers.gradleProperty("versionType").get()

val buildVersion = rootProject.extra["buildVersion"] as String
val rhinoVersion = "32395f942976a6d1d21ec9877664554cd5762306"

sourceSets.main{
    java.setSrcDirs(listOf("src/", layout.buildDirectory.dir("generated/sources/annotationProcessor/java/main")))
}

kotlin{
    sourceSets["main"].kotlin.setSrcDirs(listOf("src/"))
}

kapt{
    javacOptions{
        option("-source", "17")
        option("-target", "17")
    }
}

fun generateLocales(){
    var output = "en\n"
    val bundles = File(projectDir, "assets/bundles/")
    bundles.list()!!.sorted().forEach{ name ->
        if(name == "bundle.properties" || name == "global.properties") return@forEach
        output += name.substring("bundle".length + 1, name.lastIndexOf('.')) + "\n"
    }
    File(projectDir, "assets/locales").writeText(output)
    File(projectDir, "assets/basepartnames").writeText(
        File(projectDir, "assets/baseparts/").list()!!.sorted().filter{ it.endsWith(".msch") }.joinToString("\n")
    )
}

fun writeVersion(){
    val pfile = File(projectDir, "assets/version.properties")
    val props = Properties()

    try{
        pfile.createNewFile()
    }catch(ignored: Exception){
    }

    if(pfile.exists()){
        pfile.inputStream().use{ props.load(it) }

        println("Compiling with build: '$buildVersion'")

        props["type"] = versionType
        props["number"] = versionNumber
        props["modifier"] = providers.gradleProperty("versionModifier").get()
        props["build"] = buildVersion
        props["buildDate"] = SimpleDateFormat("MMMM d, yyyy HH:mm a", Locale.getDefault()).format(Date())
        props["commitHash"] = "unknown"
        if(project.hasProperty("showCommitHash")){
            props["commitHash"] = providers.exec{ commandLine("git", "rev-parse", "--verify", "--short", "HEAD") }.standardOutput.asText.get().trim()
        }

        pfile.bufferedWriter().use{ props.store(it, "Autogenerated file. Do not modify.") }
    }
}

fun writeServiceFile(serviceName: String, matches: (String) -> Boolean){
    File(rootDir, "annotations/src/main/resources/META-INF/services/").mkdirs()
    val serviceFile = File(rootDir, "annotations/src/main/resources/META-INF/services/$serviceName")
    val text = StringBuilder()
    val sources = File(rootDir, "annotations/src/main/java")
    sources.walkTopDown().filter{ it.isFile }.forEach{ file ->
        if(file.name.endsWith(".java") && matches(file.readText())){
            text.append(file.path.substring(sources.path.length + 1)).append("\n")
        }
    }

    serviceFile.writeText(text.toString().replace(".java", "").replace("/", ".").replace("\\", "."))
}

fun writeProcessors() = writeServiceFile("javax.annotation.processing.Processor"){ src ->
    src.contains(" extends BaseProcessor") || (src.contains(" extends AbstractProcessor") && !src.contains("abstract class"))
}

fun writePlugins() = writeServiceFile("com.sun.source.util.Plugin"){ src ->
    src.contains(" implements Plugin")
}

generateLocales()
writeVersion()
writeProcessors()
writePlugins()

val preGen = tasks.register("preGen"){
    outputs.upToDateWhen{ false }
}

tasks.compileJava{
    options.isFork = true
    dependsOn(preGen)
}

if(System.getProperty("compileMethodParams") != null){
    tasks.withType<JavaCompile>().configureEach{
        options.compilerArgs.add("-parameters")
    }
}

dependencies{
    api("at.yawk.lz4:lz4-java:1.12.0")
    api("com.github.Anuken:arc-core:frog")
    api("com.github.Anuken:rhino:$rhinoVersion")
    api("com.github.Anuken:packer:frog")

    compileOnly(project(":annotations"))
    if(!project.hasProperty("noKapt")) kapt(project(":annotations"))
}

//these are completely unnecessary
tasks.configureEach{
    if(name == "kaptGenerateStubsKotlin" || name == "compileKotlin") enabled = false
}

//comp** classes are only used for code generation
tasks.jar{
    exclude("mindustry/entities/comp/**")
}

tasks.register<Jar>("depsJar"){
    dependsOn(tasks.classes, ":server:dist")
    archiveClassifier = "deps"

    from(files(sourceSets.main.get().output.classesDirs))
    from(configurations.runtimeClasspath.map{ cfg -> cfg.map{ if(it.isDirectory) it else zipTree(it) } })
    from(zipTree("../server/build/libs/server-release.jar"))
    from(files("src/"))
    from(files("../arc/natives/natives-desktop/libs"))
    from(files("../arc/arc-core/src/"))
    from(files("../arc/extensions/arcnet/src/"))
    from(files("../arc/extensions/g3d/src/"))
    from(files("../arc/extensions/flabel/src/"))
    from(files("../arc/extensions/freetype/src/"))
    from(files("../server/src/"))

    exclude("META-INF/**")
    exclude("vfxshaders/**")
    exclude("maps/**")
    exclude("baseparts/**")
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

tasks.register<Jar>("assetsJar"){
    dependsOn(":tools:pack")
    archiveClassifier = "assets"

    into("assets"){
        from("assets")
        exclude("config", "cache", "music", "sounds", "sprites/fallback")
    }

    into("assets-raw/sprites"){
        from("assets-raw/sprites_out")
        include("**/*.png")
    }
}

tasks.register<Jar>("musicJar"){
    archiveClassifier = "music"

    into("assets"){
        from("assets")
        include("**/*.ogg", "**/*.mp3")
    }
}

val javadocBlacklist = listOf(":ios", ":desktop", ":server", ":annotations", ":android")

tasks.register<Javadoc>("mergedJavadoc"){
    fun documented() = rootProject.subprojects.filter{ p ->
        p.path !in javadocBlacklist && p.extensions.findByType<SourceSetContainer>() != null
    }

    setSource(Callable{ documented().map{ it.the<SourceSetContainer>()["main"].allJava } })
    classpath = files(Callable{ documented().map{ it.the<SourceSetContainer>()["main"].compileClasspath } })
    destinationDirectory = layout.buildDirectory.dir("javadoc")
}

java{
    withJavadocJar()
    withSourcesJar()
}

publishing{
    publications{
        create<MavenPublication>("maven"){
            from(components["java"])
        }
    }
}
