package mindustry.logic;

import arc.audio.*;
import mindustry.gen.*;

public enum LogicSound{
    artillery(Sounds.artillery),
    bang(Sounds.bang),
    bigshot(Sounds.bigshot),
    blaster(Sounds.blaster),
    bolt(Sounds.bolt),
    boom(Sounds.boom),
    breakBlock(Sounds.breaks),
    buttonClick(Sounds.buttonClick),
    cannon(Sounds.cannon),
    cannonLarge(Sounds.largeCannon),
    click(Sounds.click),
    coreExplode(Sounds.corexplode),
    door(Sounds.door),
    drillImpact(Sounds.drillImpact),
    explosion(Sounds.explosion),
    explosionBig(Sounds.explosionbig),
    explosionDull(Sounds.dullExplosion),
    explosionLarge(Sounds.largeExplosion),
    explosionTitan(Sounds.titanExplosion),
    flame(Sounds.flame),
    flame2(Sounds.flame2),
    laser(Sounds.laser),
    laserBig(Sounds.laserbig),
    laserCharge(Sounds.lasercharge),
    laserCharge2(Sounds.lasercharge2),
    laserShoot(Sounds.lasershoot),
    malignShoot(Sounds.malignShoot),
    mineDeploy(Sounds.mineDeploy),
    missile(Sounds.missile),
    missileLarge(Sounds.missileLarge),
    missileLaunch(Sounds.missileLaunch),
    missileSmall(Sounds.missileSmall),
    mud(Sounds.mud),
    noAmmo(Sounds.noammo),
    pew(Sounds.pew),
    place(Sounds.place),
    plantBreak(Sounds.plantBreak),
    plasmaBoom(Sounds.plasmaboom),
    plasmaDrop(Sounds.plasmadrop),
    pulseBlast(Sounds.pulseBlast),
    railgun(Sounds.railgun),
    release(Sounds.release),
    respawn(Sounds.respawn),
    rockBreak(Sounds.rockBreak),
    sap(Sounds.sap),
    shockBlast(Sounds.shockBlast),
    shoot(Sounds.shoot),
    shootAlt(Sounds.shootAlt),
    shootAltLong(Sounds.shootAltLong),
    shootBig(Sounds.shootBig),
    shootSmite(Sounds.shootSmite),
    shootSnap(Sounds.shootSnap),
    shotgun(Sounds.shotgun),
    spark(Sounds.spark),
    splash(Sounds.splash),
    wave(Sounds.wave),
    wind3(Sounds.wind3),
    
    beamLoop(Sounds.beam),
    bioLoop(Sounds.bioLoop),
    buildLoop(Sounds.build),
    combustionLoop(Sounds.combustion),
    conveyorLoop(Sounds.conveyor),
    cutterLoop(Sounds.cutter),
    drillLoop(Sounds.drill),
    drillChargeLoop(Sounds.drillCharge),
    extractLoop(Sounds.extractLoop),
    fireLoop(Sounds.fire),
    fluxLoop(Sounds.flux),
    glowLoop(Sounds.glow),
    grindingLoop(Sounds.grinding),
    humLoop(Sounds.hum),
    humElectricLoop(Sounds.electricHum),
    laserBeamLoop(Sounds.laserbeam),
    machineLoop(Sounds.machine),
    mineBeamLoop(Sounds.minebeam),
    missileTrailLoop(Sounds.missileTrail),
    pulseLoop(Sounds.pulse),
    rainLoop(Sounds.rain),
    respawnLoop(Sounds.respawning),
    shieldLoop(Sounds.shield),
    smelterLoop(Sounds.smelter),
    spellLoop(Sounds.spellLoop),
    sprayLoop(Sounds.spray),
    steamLoop(Sounds.steam),
    techLoop(Sounds.techloop),
    thrusterLoop(Sounds.thruster),
    torchLoop(Sounds.torch),
    tractorBeamLoop(Sounds.tractorbeam),
    windLoop(Sounds.wind),
    wind2Loop(Sounds.wind2),
    windHowlLoop(Sounds.windhowl),
    
    backUi(Sounds.back),
    chatMessageUi(Sounds.chatMessage),
    messageUi(Sounds.message),
    pressUi(Sounds.press),
    unlockUi(Sounds.unlock);
    
    public final Sound sound;

    public static final LogicSound[] all = values();
    
    LogicSound(Sound sound){
        this.sound = sound;
    }
}
