package mindustry.graphics;

import arc.graphics.*;
import arc.graphics.g2d.*;
import arc.math.*;
import arc.scene.style.*;

/**
 * Drawable for an antialiased, beveled-corner <i>outline</i>, as generated by {@link AngledCorner#outline(int, Color, float)}.
 * <p>
 * This looks similar to a {@link NinePatchDrawable} but it isn't a true nine-patch; the 4 corners are generated, the center is not drawn, and the 4 sides are drawn as lines.
 */
public class OutlinedCornerDrawable extends BaseDrawable implements TransformDrawable{
    private static final Color tmpColor = new Color();

    //quad slots within the vertex array; there is deliberately no "center" slot, as it is never drawn
    private static final int topLeft = 0, topRight = 1, bottomLeft = 2, bottomRight = 3,
        top = 4, bottom = 5, left = 6, right = 7;
    private static final int quads = 8;

    private final Color color = new Color(Color.white);
    /** Bottom tint for a top-to-bottom gradient; equal to {@link #color} unless a gradient is set. */
    private final Color color2 = new Color(Color.white);
    private final float[] vertices = new float[quads * SpriteBatch.spriteSize];
    private Texture texture;

    private float cornerSize, strokeWidth;

    /**
     * @param topLeftRegion generated corner tile for the top-left corner (flipped horizontally from the base tile)
     * @param topRightRegion generated corner tile for the top-right corner (the base tile, unflipped)
     * @param bottomLeftRegion generated corner tile for the bottom-left corner (flipped both ways)
     * @param bottomRightRegion generated corner tile for the bottom-right corner (flipped vertically)
     * @param white a plain white region, used to draw the four straight sides; must share a texture with the corners
     * @param cornerSize size of each (square) corner region, in draw-time pixels
     * @param strokeWidth thickness of the outline, in draw-time pixels
     */
    public OutlinedCornerDrawable(TextureRegion topLeftRegion, TextureRegion topRightRegion, TextureRegion bottomLeftRegion, TextureRegion bottomRightRegion, TextureRegion white, float cornerSize, float strokeWidth){

        this.texture = white.texture;
        this.cornerSize = cornerSize;
        this.strokeWidth = strokeWidth;

        setUv(topLeft, topLeftRegion);
        setUv(topRight, topRightRegion);
        setUv(bottomLeft, bottomLeftRegion);
        setUv(bottomRight, bottomRightRegion);
        setUv(top, white);
        setUv(bottom, white);
        setUv(left, white);
        setUv(right, white);

        setMinWidth(cornerSize * 2f);
        setMinHeight(cornerSize * 2f);
        setTopHeight(cornerSize);
        setBottomHeight(cornerSize);
        setLeftWidth(cornerSize);
        setRightWidth(cornerSize);
    }

    private void setUv(int quad, TextureRegion region){
        int idx = quad * SpriteBatch.spriteSize;
        float u = region.u, v = region.v2, u2 = region.u2, v2 = region.v;
        float depth = region.getDepth();
        float[] vs = vertices;

        vs[idx + 2] = u;  vs[idx + 3] = v;  vs[idx + 4] = depth;
        vs[idx + 9] = u;  vs[idx + 10] = v2; vs[idx + 11] = depth;
        vs[idx + 16] = u2; vs[idx + 17] = v2; vs[idx + 18] = depth;
        vs[idx + 23] = u2; vs[idx + 24] = v;  vs[idx + 25] = depth;
    }

    /** Sets the position of one of the eight quads, with separate bottom/top edge vertex colors. */
    private void setQuad(int quad, float x, float y, float w, float h, float colorBottom, float colorTop){
        int idx = quad * SpriteBatch.spriteSize;
        float x2 = x + w, y2 = y + h;
        float[] vs = vertices;

        vs[idx] = x;  vs[idx + 1] = y;  vs[idx + 5] = colorBottom;
        vs[idx + 7] = x;  vs[idx + 8] = y2; vs[idx + 12] = colorTop;
        vs[idx + 14] = x2; vs[idx + 15] = y2; vs[idx + 19] = colorTop;
        vs[idx + 21] = x2; vs[idx + 22] = y;  vs[idx + 26] = colorBottom;
    }

    /** @return the vertex color at absolute height {@code rowY}, lerped from {@link #color2} to {@link #color}. */
    private float rowColor(float rowY, float baseY, float totalHeight){
        float t = totalHeight > 0.0001f ? (rowY - baseY) / totalHeight : 1f;
        return tmpColor.set(color2).lerp(color, t).mul(Draw.getColor()).toFloatBits();
    }

    private void prepareVertices(float x, float y, float width, float height){
        float innerX = x + cornerSize, innerY = y + cornerSize;
        float rightX = x + width - cornerSize, topY = y + height - cornerSize;

        float cBottom = rowColor(y, y, height);
        float cBottomInner = rowColor(innerY, y, height);
        float cTopInner = rowColor(topY, y, height);
        float cTop = rowColor(y + height, y, height);

        //corners: full generated tiles, unscaled, sitting exactly in the four corners
        setQuad(bottomLeft, x, y, cornerSize, cornerSize, cBottom, cBottomInner);
        setQuad(bottomRight, rightX, y, cornerSize, cornerSize, cBottom, cBottomInner);
        setQuad(topLeft, x, topY, cornerSize, cornerSize, cTopInner, cTop);
        setQuad(topRight, rightX, topY, cornerSize, cornerSize, cTopInner, cTop);

        //sides: plain white, only as thick as the stroke, spanning the gap between corners - not the corner size
        float sideWidth = Math.max(0f, width - cornerSize * 2f);
        float sideHeight = Math.max(0f, height - cornerSize * 2f);

        setQuad(bottom, innerX, y, sideWidth, strokeWidth, cBottom, rowColor(y + strokeWidth, y, height));
        setQuad(top, innerX, y + height - strokeWidth, sideWidth, strokeWidth, rowColor(y + height - strokeWidth, y, height), cTop);
        setQuad(left, x, innerY, strokeWidth, sideHeight, cBottomInner, cTopInner);
        setQuad(right, x + width - strokeWidth, innerY, strokeWidth, sideHeight, cBottomInner, cTopInner);
    }

    @Override
    public void draw(float x, float y, float width, float height){
        CornerGenerator.uploadPending();
        prepareVertices(x, y, width, height);
        Draw.vert(texture, vertices, 0, vertices.length);
    }

    @Override
    public void draw(float x, float y, float originX, float originY, float width, float height, float scaleX, float scaleY, float rotation){
        CornerGenerator.uploadPending();
        prepareVertices(x, y, width, height);

        float worldOriginX = x + originX, worldOriginY = y + originY;
        float[] vs = vertices;
        int n = vs.length;

        if(rotation != 0){
            float cos = Mathf.cosDeg(rotation), sin = Mathf.sinDeg(rotation);
            for(int i = 0; i < n; i += SpriteBatch.vertexSize){
                float vx = (vs[i] - worldOriginX) * scaleX, vy = (vs[i + 1] - worldOriginY) * scaleY;
                vs[i] = cos * vx - sin * vy + worldOriginX;
                vs[i + 1] = sin * vx + cos * vy + worldOriginY;
            }
        }else if(scaleX != 1f || scaleY != 1f){
            for(int i = 0; i < n; i += SpriteBatch.vertexSize){
                vs[i] = (vs[i] - worldOriginX) * scaleX + worldOriginX;
                vs[i + 1] = (vs[i + 1] - worldOriginY) * scaleY + worldOriginY;
            }
        }

        Draw.vert(texture, vs, 0, n);
    }

    public float getCornerSize(){
        return cornerSize;
    }

    public float getStrokeWidth(){
        return strokeWidth;
    }

    public Color getColor(){
        return color;
    }

    /** @return the bottom tint of a top-to-bottom gradient, same as {@link #getColor()} if none is set. */
    public Color getColor2(){
        return color2;
    }

    /** Copy given color. Blended with the batch color, then combined with the texture colors at draw time. */
    public void setColor(Color color){
        this.color.set(color);
        this.color2.set(color);
    }

    /** Sets a top-to-bottom gradient tint from {@code top} to {@code bottom}. */
    public void setColor(Color top, Color bottom){
        this.color.set(top);
        this.color2.set(bottom);
    }

    /** Creates a new drawable that renders the same as this drawable tinted the specified color. */
    public OutlinedCornerDrawable tint(Color tint){
        OutlinedCornerDrawable drawable = new OutlinedCornerDrawable(this);
        drawable.color.set(tint);
        drawable.color2.set(tint);
        return drawable;
    }

    /** Creates a new drawable that renders the same as this drawable with a top-to-bottom gradient tint. */
    public OutlinedCornerDrawable tint(Color top, Color bottom){
        OutlinedCornerDrawable drawable = new OutlinedCornerDrawable(this);
        drawable.color.set(top);
        drawable.color2.set(bottom);
        return drawable;
    }

    /** Copy constructor; shares the same texture/UV data (via {@link #vertices}) as the source drawable. */
    private OutlinedCornerDrawable(OutlinedCornerDrawable other){
        super(other);
        this.texture = other.texture;
        this.cornerSize = other.cornerSize;
        this.strokeWidth = other.strokeWidth;
        this.color.set(other.color);
        this.color2.set(other.color2);
        System.arraycopy(other.vertices, 0, this.vertices, 0, other.vertices.length);
    }
}