#!/usr/bin/env bash
buildversion=-1

if [[ $# -ge 1 ]] ; then
    buildversion="$1"
else
    echo "Build version not specified, defaulting to '-1'"
    echo -e "\033[34mnote\033[0m: pass build version as the first argument: '$0' <version>"
fi

cd "$(realpath "$(dirname "$0")")" || exit 1
cd .. || exit 1

./gradlew desktop:dist -Pbuildversion="$buildversion" || exit 1

mkdir -p run/Mindustry
cd run/Mindustry || exit 1

excode=$?

if [ $excode -ne 0 ]; then
	  echo $excode
  	exit 1
fi

while true; do
#auto-restart until ctrl-c or exit 0
#if I forgot some vars, add them here, thanks
MINDUSTRY_RUNNING_VIA_SCRIPT=1 \
XDG_DATA_HOME="$(dirname "$(pwd)")" \
    java -jar -XX:+HeapDumpOnOutOfMemoryError ../../desktop/build/libs/Mindustry.jar
excode=$?
if [ $excode -eq 0 ] || [ $excode -eq 130 ]; then
  	exit 0
fi
done
